language: node_js
node_js:
  - '9'
cache:
  directories:
    - "node_modules"
script: npm start
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master